AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-app

  Sample SAM Template for sample-app
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prd
    Description: Environment name

  CustomDomainName:
    Type: String
    Default: example.com
    Description: Custom domain name

  HostedZoneId:
    Type: String
    Default: Z1234567890
    Description: Hosted zone ID

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: hello-world/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /hello
            Method: GET
      Environment:
        Variables:
          GOCACHE: /tmp/.cache/go-build
          GOPATH: /tmp/go

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

  #--------------------------------------#
  #  API Gateway
  #--------------------------------------#
  # ApiGatewayApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: Prod
  
  # Certificate:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: !Ref CustomDomainName
  #     ValidationMethod: DNS

  # ApiGatewayCustomDomain:
  #   Type: AWS::ApiGateway::DomainName
  #   Properties:
  #     DomainName: !Ref CustomDomainName
  #     CertificateArn: !Ref Certificate
  
  # ApiGatewayBasePathMapping:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     DomainName: !Ref ApiGatewayCustomDomain
  #     RestApiId: !Ref ApiGatewayApi
  #     Stage: Prod
  
  # DNSRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZoneId
  #     Name: !Ref CustomDomainName
  #     Type: A
  #     AliasTarget:
  #       DNSName: !GetAtt ApiGatewayCustomDomain.DistributionDomainName
  #       HostedZoneId: Z2FDTNDATAQYW2

