AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-app

  Sample SAM Template for sample-app
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prd
    Description: Environment name

  CustomDomainName:
    Type: String
    Description: Custom domain name

  HostedZoneId:
    Type: String
    Description: Hosted zone ID

  CertificateArn:
    Type: String
    Description: ARN of existing ACM certificate

  CookieDomain:
    Type: String
    Description: Cookie domain
    Default: ''

  AllowOrigin:
    Type: String
    Description: CORS allow origin
    Default: 'https://mydevportal.com'

  COGNITO_DOMAIN:
    Type: String
    Description: Cognito domain name
    Default: ''

  COGNITO_CLIENT_ID:
    Type: String
    Description: Cognito app client ID
    Default: ''

  COGNITO_CLIENT_SECRET:
    Type: String
    Description: Cognito app client secret
    Default: ''

  COGNITO_USER_POOL_ID:
    Type: String
    Description: Cognito user pool ID
    Default: ''

  COGNITO_CALLBACK_URL:
    Type: String
    Description: Cognito callback URL
    Default: ''

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active

Resources:
  # 明示的にAPIを定義
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      OpenApiVersion: '3.0.1'
      # CORSを静的に設定
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'https://mydevportal.com'"
        AllowCredentials: true
      DefinitionBody: !Transform 
        Name: AWS::Include
        Parameters: 
          Location: openapi.yaml

  # Custom domain
  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref CustomDomainName
      RegionalCertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  # Create an explicit API Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - HelloGet
      # HelloPostResourceは参照せず、Lambdaのイベント（HelloPost）のみ参照する
      - HelloWorldPostFunction
      - CallbackFunction
    Properties:
      RestApiId: !Ref ApiGateway
      Description: "Deployment for API Gateway"

  # API Stage (now with DeploymentId)
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      StageName: !Sub "${Environment}-apigw-1" 

  # Base path mapping (use the new ApiGateway resource)
  ApiBasePath:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
      - ApiStage
    Properties:
      DomainName: !Ref CustomDomainName
      RestApiId: !Ref ApiGateway
      Stage: !Ref Environment
      BasePath: api

  # DNS A Record
  ApiDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId

  # CORS用のGatewayResponse
  GatewayResponse4XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://mydevportal.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref ApiGateway

  GatewayResponse5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://mydevportal.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref ApiGateway

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: hello-world/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        HelloGet:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref ApiGateway
      Environment:
        Variables:
          GOCACHE: /tmp/.cache/go-build
          GOPATH: /tmp/go
          COOKIE_DOMAIN: !Ref CookieDomain
          ALLOW_ORIGIN: !Ref AllowOrigin
          
  HelloWorldPostFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: hello-world-post/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        HelloPost:
          Type: Api
          Properties:
            Path: /hello-post
            Method: POST
            RestApiId: !Ref ApiGateway
      Environment:
        Variables:
          GOCACHE: /tmp/.cache/go-build
          GOPATH: /tmp/go
          COOKIE_DOMAIN: !Ref CookieDomain
          ALLOW_ORIGIN: !Ref AllowOrigin

  CallbackFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: callback/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        Callback:
          Type: Api
          Properties:
            Path: /callback
            Method: POST
            RestApiId: !Ref ApiGateway
      Environment:
        Variables:
          GOCACHE: /tmp/.cache/go-build
          GOPATH: /tmp/go
          COOKIE_DOMAIN: !Ref CookieDomain
          ALLOW_ORIGIN: !Ref AllowOrigin
          COGNITO_DOMAIN: !Ref COGNITO_DOMAIN
          COGNITO_CLIENT_ID: !Ref COGNITO_CLIENT_ID
          COGNITO_CLIENT_SECRET: !Ref COGNITO_CLIENT_SECRET
          COGNITO_USER_POOL_ID: !Ref COGNITO_USER_POOL_ID
          COGNITO_CALLBACK_URL: !Ref COGNITO_CALLBACK_URL

  # Create a logical ID for the API method that can be referenced in DependsOn
  HelloGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations"
        
  # HelloPostResourceとHelloPostを削除し、代わりにServerlessイベントに任せる

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/

  CustomDomainUrl:
    Description: Custom domain URL
    Value: !Sub https://${CustomDomainName}/api/

  ApiGatewayRestApiId:
    Description: API Gateway REST API ID
    Value: !Ref ApiGateway

  ApiGatewayRestApiStage:
    Description: API Gateway REST API Stage
    Value: !Ref Environment